// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkwVTs6Z6jqBYYIXgvWjPGX7E3LeMfO1Y',
    appId: '1:309764999007:web:6bd8fb87c95fd86a8558ea',
    messagingSenderId: '309764999007',
    projectId: 'devhubapp-337ce',
    authDomain: 'devhubapp-337ce.firebaseapp.com',
    storageBucket: 'devhubapp-337ce.appspot.com',
    measurementId: 'G-NSJ5LWG8YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB3GESD6lr_XYa-x1r43EcwCNsZi2o66g',
    appId: '1:309764999007:android:f5816a22ada2a6ec8558ea',
    messagingSenderId: '309764999007',
    projectId: 'devhubapp-337ce',
    storageBucket: 'devhubapp-337ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtqOFgZy3mU1HQRmTOSOWwfTfiLQQr4is',
    appId: '1:309764999007:ios:e9a33ab0682fb2048558ea',
    messagingSenderId: '309764999007',
    projectId: 'devhubapp-337ce',
    storageBucket: 'devhubapp-337ce.appspot.com',
    androidClientId: '309764999007-u4jfjf5n5o4t6kp4uvt4p24pppdi98jd.apps.googleusercontent.com',
    iosClientId: '309764999007-plfqs0r749tsci10spf7esm5ooqi1lr9.apps.googleusercontent.com',
    iosBundleId: 'com.devhubkenya.devhubKenya',
  );
}
